
worker_processes 1;

events {
    # This block is required by Nginx. 1024 is the default number of connections each worker can handle.
    worker_connections 1024;
}

http {
    # this creates a pool of servers telling nginx they do the same job
    # so LOAD_BALANCING
    upstream axum {
        server rust_app_instance_1:3000;
        server rust_app_instance_2:3001;
    }

    server {
        listen 80;

        location / { 
            # so when the load balancer is run it just gets the request and forwards it to the axum pool 
            proxy_pass http://axum;

            # this gets the real ip of the user
            # since the nigix proxy calls our rust server we would get confused to know
            # who exactly created the request since al the calls would be from the nginx proxy
            # so we use this to get the info from the nginx proxy and serve in header to rust server

            # this preserves the original domain name the user has typed (mysite.com)
            proxy_set_header HOST $host;
            # this gets the real ip of the user calling nginx will be attached to the header
            proxy_set_header X-Real-IP $remote_addr;
            # the entire call trace from vpn/cloudflare (csv of every ip the request visited)
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # this is to understand of the user has used http or https 
            proxy_set_header X-Forwarded-Proto $scheme;  
        }
    }
}